name: starship-solana-devnet
version: 1.10.0

chains:
  - id: solana
    name: solana
    numValidators: 2
    ports:
      rpc: 8899
      ws: 8900
      exposer: 8001
      faucet: 9900
    resources:
      cpu: 2000m
      memory: 2048Mi

# Additional service optimization for CI
exposer:
  resources:
    cpu: 100m
    memory: 100Mi

faucet:
  resources:
    cpu: 200m
    memory: 200Mi